#ifndef CONFIG_H
#define CONFIG_H

#include <unistd.h>
#define EMULATOR_WINDOW_TITLE "Chip8 Emulator"
#define CHIP8_MEMORY_SIZE 4096
#define CHIP8_WIDTH 64
#define CHIP8_HEIGHT 32
#define CHIP8_WINDOW_MULTIPLIER 10
#define CHIP8_NUM_DATA_REGISTERS 16
#define CHIP8_TOTAL_STACK_DEPTH 16
#define CHIP8_TOTAL_KEYS 16
#define CHIP8_CHARACTER_SET_LOAD_ADDRESS 0x00
#define SAMPLE_RATE 44100
#define AUDIO_BUF_SIZE 512

#endif
